telebot:
  api-key: "your_bot_id:token"
  channel: "@<YourChannelName>"
  send_trying_count: 1
achi:
  config:
    path: /home/$USER/.achi/mainnet/config/config.yaml
wallet:
  interval: 20 #minutes
  command: "path_to/achi-blockchain/get_wallet_info.sh"
  fingerprints:
    - '<your wallet fingerprint>'
farm:
  summary:
    command: "/opt/achi-blockchain/get_farm_summary.sh"
    interval: 22 #minutes
plots:
  interval: 150 #minutes
  paths:
    - '/mnt/hdd1'
logs:
  logfile: "/var/log/achi/log.log"
  filters:
    messages:
      - '^Phase \d+ took.*$'
      - '^Total plot creation time was.*$'
      - '^Started copy to.*$'
      - '^Crafting plot.*$'
      - '^Number of Threads.*$'
      - '^Plot Name:.*$'
      - '^Working Directory:.*$'
      - '^Working Directory 2:.*$'
      - '^Copy to.*finished.*$'
    errors:
      - '^Killed$'
      - '^.*(E|e)rror.*$'
      - '^.*(E|e)xception.*$'
      - '^.*(F|f)ail.*$'
