telebot:
  api-key: "your_bot_id:token"
  channel: "@<YourChannelName>"
  send_trying_count: 1
  bot_id: "farmer1"
achi:
  config:
    path: /home/$USER/.achi/mainnet/config/config.yaml
my_wallet:
  interval: 20 #minutes
  command: "path_to/achi-blockchain/get_wallet_info.sh"
  fingerprints:
    - '<your wallet fingerprint>'
farm:
  summary:
    command: "path_to/achi-blockchain/get_farm_summary.sh"
    interval: 22 #minutes
logs:
  logfile: "/var/log/achi/log.log"
  filters:
    messages:
      - '^INFO:.*'
      - '^Phase \d+ took.*$'
      - '^Total plot creation time was.*$'
      - '^Started copy to.*$'
      - '^Crafting plot.*$'
      - '^Number of Threads.*$'
      - '^Plot Name:.*$'
      - '^Working Directory:.*$'
      - '^Working Directory 2:.*$'
      - '^Copy to.*finished.*$'
    errors:
      - '^Killed$'
      - '^.*(E|e)rror.*$'
      - '^.*(E|e)xception.*$'
      - '^.*(F|f)ail.*$'
pollings:
  log:
    is-on: true
    ding-dong-on: false
  farm:
    is-on: true
    ding-dong-on: false
  plots:
    is-on: true
    ding-dong-on: false
    interval: 1 #minutes
  wallet:
    is-on: true
    ding-dong-on: true
  heartbeat:
    is-on: false
    api: "<specify your url>"
    token: "<specify your token>"
    interval: 1 #minutes